language: node_js
node_js:
  - 'iojs-v1.5.1'
env:
  - NODE_ENV=test
before_script:
  - npm install -g gulp bower
  - bower install
  - gulp init
script:
  - gulp lint
  - gulp test
  - gulp karma-single-run